#ifndef CONSTANTS_H
#define CONSTANTS_H

//16:9 ratio
const unsigned WINDOW_WIDTH = 800;
const unsigned WINDOW_HEIGHT = 640;

//16.6 milliseconds
const unsigned FRAME_RATE = 60; 
const unsigned FRAME_TIME = 1000 / FRAME_RATE;

//TODO: replace with enum classes
enum COLLISION_TYPE{
	NO_COLLISION,
	PLAYER_ENEMY_COLLISION,
	PLAYER_VEGETATION_COLLISION,
	PLAYER_PROJECTILE_COLLSION,
	ENEMY_PROJECTILE_COLLISION,
	TARGET_COLLISION
};

enum LAYERS{
	TILEMAP_LAYER,
	VEGETATION_LAYER,
	ENEMY_LAYER,
    OBSTACLE_LAYER,
	PLAYER_LAYER,
	PROJECTILE_LAYER,
	UI_LAYER
};

const unsigned NUM_LAYERS = 7;

#endif // !CONSTANTS_H
